/**
 * class name:
 * Author
 * discriptions:
 * purpose:
 */
public class AllMyVariables {
	
	boolean isThiscorrect  = true;
    Account myAccRecords= new Account ();
	Private Date todaydate= System.today();

// method
/**
 * Method name:
 * Method Params:
 * Author
 * discriptions:
 * purpose:
 * method return:
 */
    public static Decimal calculateFinalDiscount (decimal sellingPrice , Integer discountPercent){
        //set of onstruction
			//get customerName;
			//get selingPrice;
			//calculateDiscountPercent
			//ReturnFinalPrice
	/*	Decimal finalPrice= sellingPrice-(sellingPrice * discountPercent)/100;
        return finalPrice;
        }
    public static Decimal calculateFinalDiscount (string customerType,decimal sellingPrice , Integer discountPercent){
        	if (customerType=='Retail'){
            Decimal finalPrice= sellingPrice-(sellingPrice * discountPercent)/100;
        	return finalPrice;
        							}
        	else {
			Decimal finalPrice= sellingPrice-((sellingPrice * discountPercent)/100 +(sellingPrice * 0.15));
        	return finalPrice;
    			}
  */

    MyfirstConstructor myfirstconstructoeInanotherClass = new MyfirstConstructor();
		String myAge = myfirstconstructoeInanotherClass.calculateAge(Date.newInstance(2000, 1, 1));   
    
    	System.debug(myAge);
return 0.0;
}
}