public class Manager1 extends Employee {
    
    public static void handleExcalation (){
        
    }
    public static void manageTeam(){
        
    }
    public static void manageDeliverability (){
        
    }
    public static void manageApraisals(){
        
    }
    public override void markAttendance (){
        System.debug('Mark attendance for the manager who is also employee');
    }
}